import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import MLayout from '@/layout/MLayout';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import 'sweetalert2/src/sweetalert2.scss';
import { Providers } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AntdRegistry>
					<Providers>
						<MLayout>{children}</MLayout>
					</Providers>
				</AntdRegistry>
			</body>
		</html>
	);
}
